name: verily_face_detection_example
description: Demonstrates how to use the verily_face_detection package.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  verily_face_detection:
    path: ../ # Depend on the local package
  camera: ^0.11.1 # Match the main package version
  google_mlkit_commons: ^0.11.0 # Match the main package's dependency implicitly or explicitly
  flutter_hooks: ^0.21.2 # Flutter hooks for stateful logic
  hooks_riverpod: ^2.6.1 # Added for hooks + riverpod
  permission_handler: ^11.3.1 # Added permission_handler

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
