name: verily_workspace
publish_to: none
environment:
  sdk: ^3.7.2
workspace:
  - apps/reflexy
  - apps/verily
  - apps/verily_create
  - packages/verily_device_motion
  - packages/verily_client
  - packages/verily_server
dev_dependencies:
  melos: ^7.0.0-dev.7
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint:

melos:
  repository: https://github.com/ifiokjr/verily

# All of the content of your previous melos.yaml file
# (Except for the packages and name)
