name: verily_workspace
publish_to: none
environment:
  sdk: ^3.7.2
workspace:
  - apps/reflexy
  - apps/verily
  - apps/verily_create
  - packages/verily_device_motion
  - packages/verily_face_detection
  - packages/verily_client
  - packages/verily_server
  - packages/verily_ui

dev_dependencies:
  melos: ^7.0.0-dev.8
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint:
  build_runner:
  mocktail: ^1.0.3

melos:
  repository: https://github.com/ifiokjr/verily
  scripts:
    "server:start":
      steps:
        - cd packages/verily_server
        - docker compose up --build --detach
        - dart bin/main.dart --apply-migrations
    "generate:icons":
      exec: dart run flutter_launcher_icons
      packageFilters:
        scope:
          - verily
          # - verily_create
    "generate:splash":
      exec: dart run flutter_native_splash:create
      packageFilters:
        scope:
          - verily
          # - verily_create
    analyze:
      run: melos exec --fail-fast -- flutter analyze .
      description: Run `flutter analyze` across all packages.
    format:
      run: melos exec --fail-fast -- flutter format --set-exit-if-changed .
      description: Check formatting using `flutter format --set-exit-if-changed`.


# Override analyzer version to resolve conflicts
dependency_overrides:
  analyzer: ^7.3.0 # Forcing version compatible with riverpod_generator

# All of the content of your previous melos.yaml file
# (Except for the packages and name)
