[toolchain]
# https://rust-lang.github.io/rustup-components-history/
channel = "1.85.1"
components = [
	"cargo",
	"clippy",
	"llvm-tools-preview",
	"rust-analyzer",
	"rust-src",
	"rustfmt",
]
profile = "default"
targets = ["wasm32-unknown-unknown"]
