name: verily_ui
description: Shared UI theme and components for Verily applications.
version: 0.0.1
publish_to: 'none' # Prevent accidental publishing

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0