// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiw56NwSfd2yvdYqK7qoLdlxlj3FN2YFw',
    appId: '1:105081238304:web:8ad4d80665967ad8255d45',
    messagingSenderId: '105081238304',
    projectId: 'verilyfun',
    authDomain: 'verilyfun.firebaseapp.com',
    storageBucket: 'verilyfun.firebasestorage.app',
    measurementId: 'G-RN4D1KJLV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Awl1E5HpG4UHmzZeZo-7UtQI5yvJCsk',
    appId: '1:105081238304:android:684cc0fa1b0ad2e1255d45',
    messagingSenderId: '105081238304',
    projectId: 'verilyfun',
    storageBucket: 'verilyfun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCswdt1SecJzUte2iUWQfRwYf56bKvt4S4',
    appId: '1:105081238304:ios:ab334ea7e28de19c255d45',
    messagingSenderId: '105081238304',
    projectId: 'verilyfun',
    storageBucket: 'verilyfun.firebasestorage.app',
    iosBundleId: 'fun.verily.app.verily',
  );
}
