name: verily_server
description: Starting point for a Serverpod server.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ^3.7.2

dependencies:
  serverpod: 2.5.1
  serverpod_auth_server: 2.5.1

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.5.1

resolution: workspace