name: verily_face_detection
description: A Flutter package for detecting faces using Google ML Kit, optimized
  for Verily applications. Provides real-time face detection, landmark identification,
  and classification features like smile and eye-open probabilities.
version: 0.0.1
publish_to: none
repository: https://github.com/ifiokjr/verily/tree/main/packages/verily_face_detection

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.1
  google_mlkit_commons: ^0.11.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^3.0.0
  image: ^4.1.7
  rxdart: ^0.28.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  riverpod_generator: ^2.4.0
  mockito: ^5.4.4
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
