// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

void setUrls({required String apiUrl}) =>
    RustLib.instance.api.crateApiSimpleSetUrls(apiUrl: apiUrl);

/// Call a server function
Future<AppResultString> helloWorld() =>
    RustLib.instance.api.crateApiSimpleHelloWorld();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AppResult < String >>>
abstract class AppResultString implements RustOpaqueInterface {}
