[package]
name = "verily_rpc"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { workspace = true }
server_fn = { workspace = true, features = ["reqwest"] }
verily_functions = { workspace = true, features = ["reqwest"] }
verily_core = { workspace = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
